name: Tag Validation

on:
  push:
    tags:
      - '*'

jobs:
  tag-validation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Verify SemVer format
      run: |
        TAG_VERSION=$(git tag --points-at $GITHUB_SHA)
        if ! [[ $TAG_VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Tag version is not in SemVer format (X.Y.Z): $TAG_VERSION"
          exit 1
        fi

    - name: Check package.json version
      run: |
        PACKAGE_VERSION=$(node -e "console.log(require('./package.json').version)")
        TAG_VERSION=$(git tag --points-at $GITHUB_SHA)
        if [ "$PACKAGE_VERSION" != "$TAG_VERSION" ]; then
          echo "Tag version ($TAG_VERSION) does not match package.json version ($PACKAGE_VERSION)"
          exit 1
        fi

    - name: Delete tag if validation fails
      if: failure()
      run: git push origin :refs/tags/$TAG_VERSION
